#Requires -Version 7.4
# Offline CSOM-translator regression for the Get-PnPSiteCollectionAdmin
# -Includes bug fixed in src/46-onedrive-admin.ps1.
#
# PnP.PowerShell's -Includes ValidateSet is generated by a naive reflection
# walk over the CSOM object graph and accepts dotted nested paths through a
# ClientValueObject (e.g. "AadObjectId.NameId"), but PnP.PowerShell's own
# expression builder (Utilities.DynamicExpression.ParseLambda) feeds that
# straight into CSOM's real query translator
# (Microsoft.SharePoint.Client.ClientContext.LoadQuery), which rejects that
# expression shape with InvalidQueryExpressionException. Requesting the
# bare top-level AadObjectId scalar is the only translator-accepted shape,
# and it already hydrates AadObjectId's own fields (NameId/NameIdIssuer/
# TypeId) - AadObjectId is a ClientValueObject, not partially retrievable.
#
# This script proves that against the ACTUAL installed PnP.PowerShell/CSOM
# assemblies, offline: no tenant, no auth, no credentials, no ExecuteQuery
# (the exception - when it fires - is thrown by LoadQuery itself, entirely
# client-side, before any network call). It parses src/46-onedrive-admin.ps1
# with the PowerShell AST to pull the exact -Includes argument list live
# code sends, so this test tracks the production call site instead of a
# hand-copied string list.
#
# Dependency: the PnP.PowerShell module must already be installed locally
# (the same runtime dependency the product itself has - no new dependency
# is added by this test). Skips cleanly if PnP.PowerShell is not present,
# so it never blocks the dependency-free default test run
# (tests/run-tests.ps1, which does not invoke this file).
#
# Run directly:
#   pwsh -NoProfile -File tests/onedrive-admin-csom.ps1

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$script:failures = 0
$script:passes = 0

function Write-CsomResult {
    param([string]$Name, [bool]$Pass, [string]$Detail = '')
    if ($Pass) {
        $script:passes++
        Write-Host "  PASS  $Name"
    } else {
        $script:failures++
        Write-Host "  FAIL  $Name$(if ($Detail) { " -> $Detail" })" -ForegroundColor Red
    }
}

$pnpModule = Get-Module -ListAvailable PnP.PowerShell | Select-Object -First 1
if (-not $pnpModule) {
    Write-Host 'SKIP  PnP.PowerShell module not installed locally - offline CSOM regression skipped.'
    exit 0
}
$core = Join-Path $pnpModule.ModuleBase 'Core'
$spClientDll = Join-Path $core 'Microsoft.SharePoint.Client.dll'
$spRuntimeDll = Join-Path $core 'Microsoft.SharePoint.Client.Runtime.dll'
$pnpDll = Join-Path $core 'PnP.PowerShell.dll'
if (-not (Test-Path $spClientDll) -or -not (Test-Path $spRuntimeDll) -or -not (Test-Path $pnpDll)) {
    Write-Host "SKIP  PnP.PowerShell Core assemblies not found under '$core' - offline CSOM regression skipped."
    exit 0
}

# --- Derive the actual -Includes argument list from the production source,
# via the PowerShell AST, so this test exercises the real call site rather
# than a fixed/independent expression. ---
$srcPath = Join-Path $root 'src/46-onedrive-admin.ps1'
$parseErrors = $null
$ast = [System.Management.Automation.Language.Parser]::ParseFile($srcPath, [ref]$null, [ref]$parseErrors)
if ($parseErrors) { throw "Failed to parse '$srcPath' for AST inspection." }
$calls = $ast.FindAll({
        param($n)
        $n -is [System.Management.Automation.Language.CommandAst] -and
        $n.GetCommandName() -eq 'Get-PnPSiteCollectionAdmin'
    }, $true)
if (@($calls).Count -ne 1) {
    throw "Expected exactly one Get-PnPSiteCollectionAdmin call site in '$srcPath', found $(@($calls).Count)."
}
$call = $calls[0]
$includesParamIndex = $null
for ($i = 0; $i -lt $call.CommandElements.Count; $i++) {
    $el = $call.CommandElements[$i]
    if ($el -is [System.Management.Automation.Language.CommandParameterAst] -and $el.ParameterName -eq 'Includes') {
        $includesParamIndex = $i
        break
    }
}
if ($null -eq $includesParamIndex) { throw "Get-PnPSiteCollectionAdmin call site has no -Includes parameter." }
$includesValueAst = $call.CommandElements[$includesParamIndex + 1]
$elementAsts = if ($includesValueAst -is [System.Management.Automation.Language.ArrayLiteralAst]) {
    $includesValueAst.Elements
} else {
    ,$includesValueAst
}
$productionIncludes = New-Object System.Collections.Generic.List[string]
foreach ($el in $elementAsts) {
    $text = $el.Extent.Text.Trim().TrimEnd(',').Trim()
    if ($text) { [void]$productionIncludes.Add($text) }
}
if ($productionIncludes.Count -eq 0) { throw "Could not extract any -Includes values from the production call site." }
Write-Host "Derived production -Includes from src/46-onedrive-admin.ps1: $($productionIncludes -join ', ')"

# --- Negative control: the dotted nested shape this bug was about. Proves
# the test harness itself actually detects the failure class (would have
# caught the original bug), rather than only ever asserting success. ---
$nestedControlIncludes = @('AadObjectId.NameId', 'AadObjectId.NameIdIssuer', 'UserPrincipalName')

$csSource = @'
using System;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.SharePoint.Client;
using PnPDynamicExpression = PnP.PowerShell.Commands.Utilities.DynamicExpression;

public static class SsmCsomIncludesProbe
{
    // Builds the same Expression<Func<User,object>>[] PnP.PowerShell's own
    // PnPRetrievalsCmdlet<T>.GetPropertyExpressions() builds for a given
    // -Includes string list, then runs it through the identical
    // Web.SiteUsers.Where(...).Include(...) / ClientContext.LoadQuery(...)
    // shape GetSiteCollectionAdmin.cs uses. Returns null on success, or the
    // exception type name + message on failure. Never calls ExecuteQuery -
    // no network I/O occurs.
    public static string TryLoadQuery(string[] includes)
    {
        var ctx = new ClientContext("https://contoso.invalid.example/sites/x");
        var exprs = new Expression<Func<User, object>>[includes.Length];
        for (int i = 0; i < includes.Length; i++)
        {
            exprs[i] = (Expression<Func<User, object>>)PnPDynamicExpression.ParseLambda(
                typeof(User), typeof(object), includes[i], null);
        }

        Expression<Func<User, bool>> pred = u => u.IsSiteAdmin;
        var usersQuery = System.Linq.Queryable.Where(ctx.Web.SiteUsers, pred);

        try
        {
            var included = Microsoft.SharePoint.Client.ClientObjectQueryableExtension.Include(usersQuery, exprs);
            ctx.LoadQuery(included);
            return null;
        }
        catch (Exception ex)
        {
            var e = ex;
            while (e.InnerException != null) e = e.InnerException;
            return e.GetType().FullName + ": " + e.Message;
        }
    }
}
'@

Add-Type -Path $spClientDll
Add-Type -Path $spRuntimeDll
Add-Type -Path $pnpDll
Add-Type -TypeDefinition $csSource -ReferencedAssemblies @(
    $spClientDll, $spRuntimeDll, $pnpDll,
    'System.Linq.dll', 'System.Linq.Expressions.dll', 'System.Linq.Queryable.dll',
    'System.Runtime.dll', 'netstandard.dll', 'System.Console.dll'
) -IgnoreWarnings -ErrorAction Stop

$prodResult = [SsmCsomIncludesProbe]::TryLoadQuery([string[]]$productionIncludes.ToArray())
Write-CsomResult -Name 'Production -Includes (AadObjectId, UserPrincipalName) passes the real CSOM query translator (LoadQuery), no exception' `
    -Pass ($null -eq $prodResult) -Detail $prodResult

$nestedResult = [SsmCsomIncludesProbe]::TryLoadQuery([string[]]$nestedControlIncludes)
$nestedIsExpectedFailure = $nestedResult -and $nestedResult -like 'Microsoft.SharePoint.Client.InvalidQueryExpressionException:*'
Write-CsomResult -Name 'Negative control: dotted nested AadObjectId.NameId/.NameIdIssuer is rejected by the real CSOM query translator (proves this harness detects the bug class)' `
    -Pass $nestedIsExpectedFailure -Detail $nestedResult

Write-Host ''
Write-Host "$($script:passes) passed, $($script:failures) failed (offline CSOM translator regression)"
if ($script:failures -gt 0) { exit 1 }
exit 0
